"""Add all new models for USITech database schema

Revision ID: 1cf2e17302ea
Revises: 
Create Date: 2025-10-19 15:28:34.441630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cf2e17302ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('categories', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.alter_column('comments', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('comments', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('comments', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('comments', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.alter_column('contact_messages', 'full_name',
               existing_type=sa.VARCHAR(length=160),
               nullable=False)
    op.alter_column('contact_messages', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('contact_messages', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('contact_messages', 'is_resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_contact_messages_id'), 'contact_messages', ['id'], unique=False)
    op.alter_column('favorites', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('favorites', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('favorites_user_id_workflow_id_idx'), table_name='favorites')
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_unique_constraint('uq_user_workflow_favorite', 'favorites', ['user_id', 'workflow_id'])
    op.alter_column('invoices', 'purchase_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('invoices', 'billing_name',
               existing_type=sa.VARCHAR(length=160),
               nullable=False)
    op.alter_column('invoices', 'billing_email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('SUCCESS', 'WARNING', 'ERROR', name='Enoti'),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('notifications', 'is_unread',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.alter_column('purchases', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('purchases', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('purchases', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('purchases', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'PENDING', 'REJECT', name='purchase_status'),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::purchase_status"))
    op.alter_column('purchases', 'payment_method',
               existing_type=postgresql.ENUM('QR', name='payment_method'),
               type_=sa.String(length=10),
               nullable=False,
               existing_server_default=sa.text("'QR'::payment_method"))
    op.create_index(op.f('ix_purchases_id'), 'purchases', ['id'], unique=False)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', name='user_role'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'USER'::user_role"))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('workflow_assets', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('workflow_assets', 'asset_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('workflow_assets', 'kind',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'image'::character varying"))
    op.create_index(op.f('ix_workflow_assets_id'), 'workflow_assets', ['id'], unique=False)
    op.alter_column('workflow_categories', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('workflow_categories', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('workflow_categories_workflow_id_category_id_idx'), table_name='workflow_categories')
    op.create_index(op.f('ix_workflow_categories_id'), 'workflow_categories', ['id'], unique=False)
    op.create_unique_constraint('uq_workflow_category', 'workflow_categories', ['workflow_id', 'category_id'])
    op.alter_column('workflows', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('workflows', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('workflows', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('workflows', 'status',
               existing_type=postgresql.ENUM('active', 'expired', name='workflow_status'),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::workflow_status"))
    op.alter_column('workflows', 'downloads_count',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('workflows', 'video_demo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('workflows', 'flow',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.alter_column('workflows', 'flow',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('workflows', 'video_demo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('workflows', 'downloads_count',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('workflows', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('active', 'expired', name='workflow_status'),
               nullable=True,
               existing_server_default=sa.text("'active'::workflow_status"))
    op.alter_column('workflows', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('workflows', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('workflows', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_constraint('uq_workflow_category', 'workflow_categories', type_='unique')
    op.drop_index(op.f('ix_workflow_categories_id'), table_name='workflow_categories')
    op.create_index(op.f('workflow_categories_workflow_id_category_id_idx'), 'workflow_categories', ['workflow_id', 'category_id'], unique=True)
    op.alter_column('workflow_categories', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('workflow_categories', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_workflow_assets_id'), table_name='workflow_assets')
    op.alter_column('workflow_assets', 'kind',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'image'::character varying"))
    op.alter_column('workflow_assets', 'asset_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('workflow_assets', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('USER', 'ADMIN', name='user_role'),
               existing_nullable=True,
               existing_server_default=sa.text("'USER'::user_role"))
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_purchases_id'), table_name='purchases')
    op.alter_column('purchases', 'payment_method',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('QR', name='payment_method'),
               nullable=True,
               existing_server_default=sa.text("'QR'::payment_method"))
    op.alter_column('purchases', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('ACTIVE', 'PENDING', 'REJECT', name='purchase_status'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::purchase_status"))
    op.alter_column('purchases', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('purchases', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('purchases', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.alter_column('notifications', 'is_unread',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('notifications', 'type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('SUCCESS', 'WARNING', 'ERROR', name='Enoti'),
               nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.alter_column('invoices', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoices', 'billing_email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('invoices', 'billing_name',
               existing_type=sa.VARCHAR(length=160),
               nullable=True)
    op.alter_column('invoices', 'purchase_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('uq_user_workflow_favorite', 'favorites', type_='unique')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.create_index(op.f('favorites_user_id_workflow_id_idx'), 'favorites', ['user_id', 'workflow_id'], unique=True)
    op.alter_column('favorites', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('favorites', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    op.alter_column('contact_messages', 'is_resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('contact_messages', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('contact_messages', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('contact_messages', 'full_name',
               existing_type=sa.VARCHAR(length=160),
               nullable=True)
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.alter_column('comments', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('comments', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('comments', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('comments', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('comments', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.alter_column('categories', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
