"""Add wallet system tables

Revision ID: ea82ecd7c2c5
Revises: 1cf2e17302ea
Create Date: 2025-10-22 13:54:45.549595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea82ecd7c2c5'
down_revision = '1cf2e17302ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_transactions', 'wallet_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('wallet_transactions', 'transaction_type',
               existing_type=postgresql.ENUM('DEPOSIT', 'PURCHASE', 'REFUND', name='transaction_type'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('wallet_transactions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', name='transaction_status'),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::transaction_status"))
    op.drop_index(op.f('idx_wallet_tx_wallet_created'), table_name='wallet_transactions')
    op.create_index('idx_wallet_transactions_wallet_created', 'wallet_transactions', ['wallet_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.drop_constraint(op.f('wallet_transactions_wallet_id_fkey'), 'wallet_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'wallet_transactions', 'wallets', ['wallet_id'], ['id'])
    op.alter_column('wallets', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('wallets', 'balance',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('wallets', 'total_deposited',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('wallets', 'total_spent',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.drop_constraint(op.f('wallets_user_id_fkey'), 'wallets', type_='foreignkey')
    op.create_foreign_key(None, 'wallets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.create_foreign_key(op.f('wallets_user_id_fkey'), 'wallets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.alter_column('wallets', 'total_spent',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('wallets', 'total_deposited',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('wallets', 'balance',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('wallets', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'wallet_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('wallet_transactions_wallet_id_fkey'), 'wallet_transactions', 'wallets', ['wallet_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_index('idx_wallet_transactions_wallet_created', table_name='wallet_transactions')
    op.create_index(op.f('idx_wallet_tx_wallet_created'), 'wallet_transactions', ['wallet_id', 'created_at'], unique=False)
    op.alter_column('wallet_transactions', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', name='transaction_status'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::transaction_status"))
    op.alter_column('wallet_transactions', 'transaction_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('DEPOSIT', 'PURCHASE', 'REFUND', name='transaction_type'),
               existing_nullable=False)
    op.alter_column('wallet_transactions', 'wallet_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
